# Generated by Django 2.1.7 on 2019-03-21 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='上传时间'),
        ),
    ]
