# Generated by Django 2.1.7 on 2019-03-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=5, verbose_name='性别')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='书名')),
                ('pub_date', models.DateField(verbose_name='出版日期')),
                ('price', models.FloatField(verbose_name='价格')),
                ('book_type', models.CharField(choices=[('Science fiction', '科幻小说'), ('Suspense novel', '悬疑小说'), ('Romantic novels', '言情小说'), ('Other novels', '其他小说')], default='Other novels', max_length=50, verbose_name='种类')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_demo.Author')),
            ],
            options={
                'db_table': 'book',
                'ordering': ('-pub_date',),
            },
        ),
    ]
