# Generated by Django 2.1.7 on 2019-03-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nicename',
            field=models.CharField(blank=True, default='莫得感情的杀手', max_length=32, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, max_length=128, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最新一次更改'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='电话号码'),
        ),
    ]
